---
engines:
  scss-lint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
    channel: beta
ratings:
  paths:
    - '**.tsx'
    - '**.ts'
    - '**.jsx'
    - '**.js'
    - '**.css'
    - '**.scss'
exclude_patterns:
  - 'test/'
  - '**/*.test.*'
  - 'node_modules/'
  - 'src/graphql-types.d.ts'
